#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: capstone
#    volumes:
#      - /Users/kjh/Downloads/Docker_Sql:/var/lib/mysql
##      - ./my.cnf:/etc/mysql/conf.d/my.cnf
#    ports:
#      - "3306:3306"
##    command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve
##    restart: always
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    environment:
#      DB_HOST: mysql
#      DB_PORT: 3306
#      DB_NAME: capstone
#      DB_USER: root
#      DB_PASSWORD: 1234
#
## volumes:  # 이 부분은 더 이상 필요하지 않으므로 주석 처리
##   mysql-data:
