name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build JAR
      run: ./gradlew clean build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: build/libs/app.jar

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        # 파일 복사
        scp -i $KEY build/libs/app.jar docker-compose.yml Dockerfile $USER@$HOST:/home/ubuntu/

        # EC2에 연결하여 도커 컴포즈 실행
        ssh -i $KEY $USER@$HOST << 'EOF'
          # cd /home/ubuntu
          docker-compose down || true
          docker-compose up -d
        EOF
